package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"time"
)

func main() {
	fmt.Println("Welcome to File bro")
	content := "File Executed last Time : "

	file, err := os.Create("./newAutoGeneratedFile.txt")
	if err != nil {
		// Nothing but the Printing Statement
		panic(err)
	}

	// write using the Io operations
	length, err := io.WriteString(file, content+" "+time.Now().String())
	if err != nil {
		// Nothing but the Printing Statement
		panic(err)
	}
	fmt.Printf("Length %v", length)

	defer file.Close()

	readFile("./newAutoGeneratedFile.txt")

}

func readFile(filename string) {
	databyte, err := ioutil.ReadFile(filename)

	checkNilErr(err)
	fmt.Println("File Content", databyte)
}

func checkNilErr(err error) {
	panic(err)
}
